# Generated by Django 5.2.6 on 2025-09-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('sentimento', models.CharField(max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
